<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\version"></Import>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Brian Griggs</Authors>
		<Company>Big Mission Motorsports, LLC</Company>
		<Product>Red Mist</Product>
		<Copyright>2026</Copyright>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RedMist.Backend.Shared\RedMist.Backend.Shared.csproj" />
		<ProjectReference Include="..\RedMist.Database\RedMist.Database.csproj" />
	</ItemGroup>

</Project>
