apiVersion: v2
name: redmist-timing
description: Deploy redmist timing backend
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: "20.9.0"
    repository: oci://registry-1.docker.io/bitnamicharts