# Production Environment Configuration
global:
  env:
    "ASPNETCORE_ENVIRONMENT": "Production"
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"
    "ASPNETCORE_URLS": "http://+:8080"
    "REDIS_SVC": "redis-master:6379"
    "Keycloak__Realm": "redmist"
    "Keycloak__AuthServerUrl": "https://auth.redmist.racing"
    "SentinelApiUrl": "https://svs-api.sentinel.racing/api/"
    "Server__ExtTelemUrl": "https://api.redmist.racing/status/v1/ExternalTelemetry"

# Override for all subcharts
redmist-status-api:
  environment: prod
  serviceMonitor:
    enabled: true
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    keda:
      enabled: true
      prometheusServerAddress: http://prometheus-kube-prometheus-prometheus.monitoring:9090
      cooldownPeriod: 300
      podsWhenLive: 2
      targetConnectionsPerPod: 50

redmist-event-orchestration:
  serviceMonitor:
    enabled: true

redmist-relay-api:
  environment: prod
  serviceMonitor:
    enabled: true

redmist-event-management:
  environment: prod
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    keda:
      enabled: true
      prometheusServerAddress: http://prometheus-kube-prometheus-prometheus.monitoring:9090
      cooldownPeriod: 300
      podsWhenActive: 2
  serviceMonitor:
    enabled: true

redmist-external-data-collection:
  autoscaling:
    enabled: true
    keda:
      enabled: true
      prometheusServerAddress: http://prometheus-kube-prometheus-prometheus.monitoring:9090
      cooldownPeriod: 300

# Redis configuration for production (using Redis Operator)
redis:
  name: "redis"
  replicas: 2
  
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
  
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "800Mi"
  
  auth:
    secretName: "rmkeys"
    secretKey: "redis"
  
  customConfig:
    - "maxmemory-policy allkeys-lru"
    - "appendonly no"
