// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedMist.Database;

#nullable disable

namespace RedMist.Database.Migrations
{
    [DbContext(typeof(TsContext))]
    [Migration("20260208011209_DriverInfo")]
    partial class DriverInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RedMist.Database.Models.CarLapLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("Flag")
                        .HasColumnType("integer");

                    b.Property<string>("LapData")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CarLapLogs");
                });

            modelBuilder.Entity("RedMist.Database.Models.CarLastLap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("LastLapNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastLapTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CarLastLaps");
                });

            modelBuilder.Entity("RedMist.Database.Models.DefaultOrgImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("DefaultOrgImages");
                });

            modelBuilder.Entity("RedMist.Database.Models.DriverInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("FlagtronicsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FlagtronicsId")
                        .IsUnique();

                    b.ToTable("DriverInfo");
                });

            modelBuilder.Entity("RedMist.Database.Models.EventStatusLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("EventStatusLogs");
                });

            modelBuilder.Entity("RedMist.Database.Models.FlagLog", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Flag")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("EventId", "SessionId", "Flag", "StartTime");

                    b.ToTable("FlagLog");
                });

            modelBuilder.Entity("RedMist.Database.Models.GoogleSheetsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.ToTable("GoogleSheetsConfigs");
                });

            modelBuilder.Entity("RedMist.Database.Models.RelayLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("RelayLogs");
                });

            modelBuilder.Entity("RedMist.Database.Models.SessionResult", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("ControlLogs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionState")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("EventId", "SessionId");

                    b.ToTable("SessionResults");
                });

            modelBuilder.Entity("RedMist.Database.Models.UserOrganizationMapping", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Username", "OrganizationId");

                    b.ToTable("UserOrganizationMappings");
                });

            modelBuilder.Entity("RedMist.TimingCommon.Models.CompetitorMetadata", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("e");

                    b.Property<string>("CarNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasJsonPropertyName("n");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasJsonPropertyName("cl");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("c");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasJsonPropertyName("a");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("fn");

                    b.Property<string>("Hometown")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasJsonPropertyName("h");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("ln");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("lu");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasJsonPropertyName("mk");

                    b.Property<string>("ModelEngine")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasJsonPropertyName("mo");

                    b.Property<string>("NationState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasJsonPropertyName("ns");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("s");

                    b.Property<string>("Tires")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasJsonPropertyName("tr");

                    b.Property<long>("Transponder")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("t");

                    b.Property<long>("Transponder2")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("t2");

                    b.HasKey("EventId", "CarNumber");

                    b.ToTable("CompetitorMetadata");
                });

            modelBuilder.Entity("RedMist.TimingCommon.Models.Configuration.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Broadcast")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CourseConfiguration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EnableSourceDataLogging")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("boolean");

                    b.Property<string>("LoopsMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RedMist.TimingCommon.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ControlLogParams")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ControlLogType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FlagtronicsApiKey")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("FlagtronicsUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("Logo")
                        .HasMaxLength(5242880)
                        .HasColumnType("bytea");

                    b.Property<string>("MultiloopIp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MultiloopPort")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrbitsLogsPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RMonitorIp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("RMonitorPort")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RelayLastConnected")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RelayVersion")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("ShowControlLogConnection")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFlagtronicsConnection")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowMultiloopConnection")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowOrbitsLogsConnection")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowX2Connection")
                        .HasColumnType("boolean");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("X2")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("RedMist.TimingCommon.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("sid");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("eid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("et");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("il");

                    b.Property<bool>("IsPracticeQualifying")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("pq");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("lu");

                    b.Property<double>("LocalTimeZoneOffset")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("tz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("n");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("st");

                    b.HasKey("Id", "EventId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RedMist.TimingCommon.Models.X2.Loop", b =>
                {
                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("HasActivity")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDeviceErrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDeviceWarnings")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInPit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSyncOk")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude0")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude1")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude0")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude1")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId", "EventId", "Id");

                    b.ToTable("X2Loops");
                });

            modelBuilder.Entity("RedMist.TimingCommon.Models.X2.Passing", b =>
                {
                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("o");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("e");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("i");

                    b.Property<int>("Hits")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("h");

                    b.Property<bool>("IsInPit")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("p");

                    b.Property<bool>("IsResend")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("r");

                    b.Property<long>("LoopId")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("l");

                    b.Property<DateTime>("TimestampLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("tl");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("tu");

                    b.Property<long>("TransponderId")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("t");

                    b.Property<long>("TransponderShortId")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ts");

                    b.HasKey("OrganizationId", "EventId", "Id");

                    b.ToTable("X2Passings");
                });

            modelBuilder.Entity("RedMist.TimingCommon.UIVersionInfo", b =>
                {
                    b.Property<bool>("IsAndroidMinimumMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIOSMinimumMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebMinimumMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestAndroidVersion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LatestIOSVersion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LatestWebVersion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("MinimumAndroidVersion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("MinimumIOSVersion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("MinimumWebVersion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("RecommendAndroidUpdate")
                        .HasColumnType("boolean");

                    b.Property<bool>("RecommendIOSUpdate")
                        .HasColumnType("boolean");

                    b.Property<bool>("RecommendWebUpdate")
                        .HasColumnType("boolean");

                    b.ToTable("UIVersions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
