replicaCount: 1

image:
  repository: bigmission/redmist-ui-browser
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "Upgrade $http_upgrade";
    #   more_set_headers "Connection $http_connection";
    #   more_set_headers "Host $host";
    #   more_set_headers "X-Forwarded-For $proxy_add_x_forwarded_for";
    #   more_set_headers "X-Forwarded-Proto $scheme";
    #   proxy_cache_bypass $http_upgrade;
  hosts:
  - host: sunnywood.redmist.racing
    paths: 
    - path: /timingui(/|$)(.*)
      pathType: Prefix
  tls:
  - hosts:
    - sunnywood.redmist.racing
    secretName: redmist-timing-tls

autoscaling:
  enabled: false

serviceAccount:
  create: false

env:
