apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "redmist-post-event-reports.fullname" . }}
  labels:
    {{- include "redmist-post-event-reports.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  suspend: {{ .Values.suspend }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "redmist-post-event-reports.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "redmist-post-event-reports.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "redmist-post-event-reports.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
              {{- $env := merge (.Values.env | default dict) (.Values.global.env | default dict) -}}
              {{ range $k, $v := $env }}
                - name: {{ $k | quote }}
                  value: {{ $v | quote }}
              {{- end }}
              {{ range .Values.global.secrets }}
                - name: {{ .env | quote }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .name }}
                      key: {{ .key }}
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
