{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redmist-status-api.fullname" . }}
  labels:
    {{- include "redmist-status-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redmist-status-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
{{- end }}
