{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redmist-event-management.fullname" . }}
  labels:
    {{- include "redmist-event-management.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redmist-event-management.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
{{- end }}
