replicaCount: 1

image:
  repository: bigmission/redmist-relay-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  # Environment-specific configuration
  environment: prod  # Override this in environment-specific values files
  domain: redmist.racing
  subdomain: api
  hosts:
  - paths: 
    - path: /relay/(.*)
      pathType: ImplementationSpecific
  tls: false

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "180Mi"
  limits:
    cpu: "300m"
    memory: "500Mi"

serviceAccount:
  create: false

env:
  PathBase: "/relay"
